### ISSUE TITLE
AudioProcessing.java line 145 may be some minor errors?

### ISSUE THREAD

**Issue by zuowanbushiwo** [mail2chromium/Android-Audio-Processing-Using-WebRTC#4]
Thank you very much for the open source project, this helped me a lot。I analyze the source code，find  that
   _dataSocket = new DatagramSocket(Integer.parseInt(vm.getTargetPort()), localAddr); 
   maybe change to
   _dataSocket = new DatagramSocket(PORT, localAddr); 
   Is that right?

**Comment by mail2chromium** [comment]
Well, it's working fine as I am getting port from a UI text view. So, in the end, things meet at the same level of understanding.

**Comment by zuowanbushiwo** [comment]
thanks，Is that port used for debugging? Is there any debugging software on the PC? Can it be analyzed in real time?

**Comment by mail2chromium** [comment]
As the main purpose of this Audio Processing module is to obtain low-level processing of Audio signals and improve the overall audio quality. This APM module was extracted from WebRtc and is developed in `C/C++`. You can tweak this code to make it efficient on the PCs as well.

I hope I will also update this feature coming soon so that anyone can use it on any of the available platforms such as iOS, Browsers, and PCs as well.

**Comment by zuowanbushiwo** [comment]
Thanks！And watching
